# Generated by Django 5.2.6 on 2025-09-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="changed_date",
            new_name="updated_at",
        ),
    ]
